<a href="https://colab.research.google.com/github/Betty987/pytorch_deeplearning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [2]:
!nvidia-smi

Wed Sep  7 01:32:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
##introduction to tensors
#creating a tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([4,3])
vector

tensor([4, 3])

In [7]:
vector.ndim#1d array


1

In [8]:
#matrix
matrix=torch.tensor([[3,4],
                     [4,9]])
matrix



tensor([[3, 4],
        [4, 9]])

In [9]:
matrix.ndim#2d array

2

In [10]:
matrix.shape#shape tells you how many rows and cols


torch.Size([2, 2])

In [11]:
#tensor
tensor=torch.tensor([[[1,2],[3,4],[5,6]]])
tensor

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [12]:
#ndim basically tells the number of square bracket pairs
tensor.ndim


3

In [13]:
tensor=torch.tensor([[[[1,2,3],
                       [4,5,6],
                       [7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [14]:
tensor.ndim

4

In [15]:
tensor[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor.shape

torch.Size([1, 1, 3, 3])

###random tenesors


In [17]:
random_tensor=torch.rand(3,4)#creates a random tensor of 3 rows and 4 cols
random_tensor

tensor([[0.2915, 0.8123, 0.5685, 0.5253],
        [0.9500, 0.9634, 0.7682, 0.1046],
        [0.6228, 0.0187, 0.7340, 0.3944]])

In [18]:
random_tensor.ndim


2

In [19]:
#create a random tensor with similar shape to an image tensor
random_image_tensor=torch.rand(size=(1,2,3)) #height,width and color channels(R,G,B)
random_image_tensor


tensor([[[0.0230, 0.7845, 0.5240],
         [0.6593, 0.9304, 0.6734]]])

In [20]:
#zeroes and ones
zero=torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
one=torch.ones(3,4)
one


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zero*one

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#range


In [23]:
range=torch.arange(start=0,end=10,step=3)#prints the numbers within range

In [24]:
#creating tensors like
range_like=torch.zeros_like(input=range)
range_like

tensor([0, 0, 0, 0])

Tensor data types

In [25]:
int64_tensor=torch.tensor([3,2],dtype=None,device=None,requires_grad=False)
int64_tensor.dtype


torch.int64

In [26]:
float_32_tensor=int64_tensor.type(torch.float32)
float_32_tensor.dtype


torch.float32

In [27]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

#getting info from tensors

In [28]:
#to get datatype=tensor.dtype
#to get shape=tensor.shape
#to get device(Cpu or gpu)=tensor.device

In [29]:
some_tensor=torch.rand(3,4)
some_tensor.shape,some_tensor.device,some_tensor.dtype


(torch.Size([3, 4]), device(type='cpu'), torch.float32)

In [30]:
#manipulating tensors(tensor operations)
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [31]:
torch.mul(tensor,10)

tensor([10, 20, 30])

#matrix multiplication


In [32]:
#element wise multipication
print(f"Equals: {tensor*tensor}")

Equals: tensor([1, 4, 9])


In [33]:
#matrix multiplication
torch.matmul(tensor,tensor).item()

14

In [34]:
tensor


tensor([1, 2, 3])

In [71]:
#matrix mul using for loop
'''
sum=0
for i in range(len(tensor)):
  sum+=tensor[i]*tensor[i]
print(sum)
'''

'\nsum=0\nfor i in range(len(tensor)):\n  sum+=tensor[i]*tensor[i]\nprint(sum)\n'

In [36]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8965, 0.5888, 0.1980],
        [0.7857, 0.5111, 0.1707],
        [0.5123, 0.3264, 0.1073]])

In [37]:
new_tensor=torch.rand(3,2)
new_tensor

tensor([[0.6358, 0.3320],
        [0.5575, 0.6638],
        [0.0942, 0.7809]])

In [38]:
#transpose
#to fix tensor shape issues,we can manipulate shape using transpose

tensor_transpose=new_tensor.T
tensor_transpose

tensor([[0.6358, 0.5575, 0.0942],
        [0.3320, 0.6638, 0.7809]])

In [39]:
#finding the min,mean,sum(tensor aggregation)
min=torch.min(new_tensor)
max=torch.max(new_tensor)
mean=torch.mean(new_tensor)
sum=torch.sum(new_tensor)
min,max,mean,sum


(tensor(0.0942), tensor(0.7809), tensor(0.5107), tensor(3.0642))

In [40]:

new_tensor

tensor([[0.6358, 0.3320],
        [0.5575, 0.6638],
        [0.0942, 0.7809]])

In [41]:
x=torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#find positional min and max =find the index where min and max is
x.argmin(),x.argmax()

(tensor(0), tensor(9))

#reshaping,stacking,squeezing and unsqueezing tensors

In [43]:
#reshaping
x.reshape(10,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [44]:
#change the view
z=x.view(1,10)
z

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
#stack tensors
x_sstacked=torch.stack([x,x,x],dim=1)
x_sstacked

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [46]:
#squeeze tensors==removes all the single dimensions
a=torch.rand(1,3)
a.shape

torch.Size([1, 3])

In [47]:
a_squeeze=a.squeeze().shape

In [49]:
#permute=rearranges the dimensions
x=torch.rand(223,221,3) 
x_permuted=x.permute(2,0,1)
print(f"original{x.shape}")
print(f"original{x_permuted.shape}")

originaltorch.Size([223, 221, 3])
originaltorch.Size([3, 223, 221])


In [50]:
array=np.arange(1.0,10.0)
array.dtype

dtype('float64')

In [51]:
#turns numpy array to tensor
tensor=torch.from_numpy(array)
tensor.dtype

torch.float64

In [53]:
#reproducability
#randomseed==to make a flavored randomness

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensorC=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensorD=torch.rand(3,4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC==random_tensorD)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#running tensors and pytroch objects on the GPU(faster computation)

In [54]:
!nvidia-smi

Wed Sep  7 01:52:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##gettting a GPU
1.google colab
2.use your own Gpu
3 use cloud computing

In [55]:
#check for gpu access with pytroch
import torch
torch.cuda.is_available()

True

In [62]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [63]:
#count number of devices
torch.cuda.device_count()

1

In [64]:
#putting tensors and models on the gpu
#the reason we are using gpu is for faster computation
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [66]:
#move tensor to gpu
tensor_ongpu=tensor.to(device)
tensor_ongpu

tensor([1, 2, 3], device='cuda:0')

In [70]:
#numpy only works on cpu so we need to move it back to cpu
tensor_cpu=tensor_ongpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])